### ISSUE TITLE
Remove drifting noise

### ISSUE THREAD

**Issue by JuanFMontesinos** [RF5/simple-autovc#2]
Hi
I've seen you apply a filter to remove this noise.
I'm not aware of what does drifting noise is. Could you provide some references?

Thanks!

**Comment by RF5** [comment]
Hi

I am not entirely certain myself what it refers to in this scenario, but drift noise typically refers to the phenomenon that over long periods of time, the zero-point for a microphone might change. For example, if perfectly silent audio is recorded as a sample of 0, then at the end of a long utterance the perfect silence might be recorded as 0.001 (i.e the zero-point has drifted). The high-pass filter is intended to remove any possible drift, especially since speech has relatively little information content below e.g. 10Hz. 

The reason I include it here is that the original authors use it in their data preprocessing [here](https://github.com/auspicious3000/autovc/blob/master/make_spect.py) -- they don't describe the filtering reasoning or parameters in the paper or in the repo, so I am not exactly sure why they chose this filter design in particular, but I kept it the same to be as close to the original authors implementation as possible.

Hope that helps!

**Comment by RF5** [comment]
Closing now since this seems a bit dead. Feel free to open again if you are still having issues.

**Comment by JuanFMontesinos** [comment]
Thank you very much for the info (and sorry, you just caught me before vacation) 
I was expecting to use the vocoder (as it's trained for 16k audios) but the preprocessing relies on 
https://github.com/RF5/simple-autovc/blob/master/spec_utils.py#L44-67 this preprocessing steps rather thank vectorized (gpu) functions from pytorch. 

I will try to port it to use the model without retraining. If I'm sucessful I can merge a PR as it would be more convinient for you I think. 

Best and thanks
Juan

**Comment by RF5** [comment]
Sure if it improves upon things I'll be happy to merge, feel free to open a PR if you get something working 👍
