### ISSUE TITLE
Fine-Tuning

### ISSUE THREAD

**Issue by CCMaure** [RF5/simple-autovc#5]
Hello,
thanks for your nice work. It actually gives reasonable output. Currently my output just sounds quite simlar to the source Audio with little to no hearable aspects of the target.
Do you have a tipp to get better results?
Is it necessary to fine-tune the hifigan model. And if, can you give longer explanation on how to do so? Which Spectrograms need to be paired with the ground truth and how many samples are needed for a good result?

Kind Regards
Mr Maure

**Comment by RF5** [comment]
Hi

I find the autovc model doesn't really do well outside of the dataset it is trained on. I think the hifigan model is probably not the issue, it is likely autovc. I would recommend fine-tuning autovc on a dataset containing your desired speaker. I have never tried it, so don't know exactly the best way to go about it or how many samples would ideally be needed. Perhaps the original authors of the paper might know some more extensions that may improve things? 

Otherwise, if you want just good voice conversion out-of-the-box, I have a newer model [here](https://github.com/bshall/knn-vc) that might be of help.

Hope that helps!
